# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install project dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application files to the container
COPY . /app

# Expose the port that Streamlit will use
EXPOSE 8501

# Start the Streamlit application
CMD ["streamlit", "run", "main.py"]
