# Use an official Python runtime as a parent image
FROM python:3.8-slim-buster

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file to the container
COPY requirements.txt .

# Install project dependencies
RUN pip install -r requirements.txt

# Copy the rest of the application files to the container
COPY . /app

# Start the client-kafka application server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
